title: Chip Kastner
description: Github

theme: minima

url: https://chip-kastner.github.io
baseurl: ""

# Navigation (keep it simple)
header_pages:
  - index.md

# plugins:
#  - jekyll-seo-tag

# Build settings
markdown: kramdown
permalink: pretty

# Optional minima styling
minima:
  skin: auto
  date_format: "%b %-d, %Y"
